### ISSUE TITLE
Fuzzing HTTP server on Windows - TimeoutError: [WinError 10060]

### ISSUE THREAD

**Issue by starek4** [jtpereyda/boofuzz#281]
Hi,

I am trying to fuzz HTTP server. I use SocketConnection with `proto` set to "tcp". I need to get a response from tested target so I am using callback function (passed via `post_test_case_callbacks` argument to Session). In the callback function, I just call `target.rcv()` for getting the response.

There is a problem when the server reset a connection. In the Wireshark it looks like this:
![reset](https://user-images.githubusercontent.com/2153835/58629881-f87f8200-82dd-11e9-91b1-eefc1bf35730.png)

`recv()` function throws this:
```
Error!!!! A custom post_send callback function raised an uncought error.
Traceback (most recent call last):
File "[...]\AppData\Local\Programs\Python\Python37-32\lib\site-packages\boofuzz\socket_connection.py", line 186, in recv
    data = self._sock.recv(max_bytes)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "[...]\AppData\Local\Programs\Python\Python37-32\lib\site-packages\boofuzz\sessions.py", line 1484, in _post_send
    f(target=target, fuzz_data_logger=self._fuzz_data_logger, session=self, sock=target)
File "[...]\Desktop\repos\ysoft_fuzzer\fuzzer\src\post_test_case_callback.py", line 15, in post_test_callback
    response_string = target.recv()
File "[...]\AppData\Local\Programs\Python\Python37-32\lib\site-packages\boofuzz\sessions.py", line 134, in recv
    data = self._target_connection.recv(max_bytes=max_bytes)
File "[...]\AppData\Local\Programs\Python\Python37-32\lib\site-packages\boofuzz\socket_connection.py", line 208, in recv
    raise_(exception.BoofuzzTargetConnectionReset, None, sys.exc_info()[2])
File "[...]\AppData\Local\Programs\Python\Python37-32\lib\site-packages\future\utils\__init__.py", line 415, in raise_
    raise exc.with_traceback(tb)
TypeError: descriptor 'with_traceback' requires a 'BaseException' object but received a 'traceback'
```

I would like to parse the response even if server reset connection at the end. It does not work only on Windows machine, on Linux it works fine. In version 0.1.4 (on Python 2) it can be solved by calling target.recv() after few milliseconds (just `time.sleep()` before calling `recv()`) and I was able to get the answer without an exception. In 0.1.5 (on Python 3) this no longer works (even after a longer period of time and ignoring exceptions, nothing is received). I use the same target and code on both Linux (WSL, Ubuntu 18.04, Python 3.6.7) and Windows (W10, latest build, Python 3.7.2) machine.

I tried to set `ignore_connection_reset` to `True`, but nothing changed.

Could someone help me with this?

**Comment by starek4** [comment]
Minimal example, which sometimes throws that exception as I mention before:

server code for python 2 (executed on WSL, Ubuntu 18.04, Python 2.7.15rc1)
```
from BaseHTTPServer import BaseHTTPRequestHandler, HTTPServer


class S(BaseHTTPRequestHandler):
    def _set_headers(self):
        self.send_response(200)
        self.send_header('Content-type', 'text/html')
        self.end_headers()

    def do_GET(self):
        self._set_headers()
        self.wfile.write("<html><body><h1>hi!</h1></body></html>")


def run(server_class=HTTPServer, handler_class=S, port=5050):
    server_address = ('', port)
    httpd = server_class(server_address, handler_class)
    print('Starting httpd...')
    httpd.serve_forever()

if __name__ == "__main__":
    from sys import argv

    if len(argv) == 2:
        run(port=int(argv[1]))
    else:
        run()
```

fuzzer code for python 3 (executed on Windows 10, Python 3.7.2)
```
from boofuzz import *


def post_test_callback(target, fuzz_data_logger, session, sock, *args, **kwargs):
    _ = target.recv()
    

def main():
    session = Session(
        post_test_case_callbacks=[post_test_callback],
        target=Target(
            connection=SocketConnection("127.0.0.1", 5050, proto='tcp')
        ),
    )

    s_initialize(name="Request")
    with s_block("Request-Line"):
        s_group("Method", ['GET'])
        s_delim(" ", name='space-1')
        s_string("/index.html", name='Request-URI')
        s_delim(" ", name='space-2')
        s_string('HTTP/1.1', name='HTTP-Version')
        s_static("\r\n", name="Request-Line-CRLF")
    s_static("\r\n", "Request-CRLF")

    session.connect(s_get("Request"))

    session.fuzz()


if __name__ == "__main__":
    main()

```

**Comment by SR4ven** [comment]
How long do you usually run the test until you get an error?
On Ubuntu 18.10, Python 3.6.8 with the target on the same machine with Python 2.7.16 the test completed without errors. Same for both on Python 2.7.16
Are target and fuzzer on separate machines in your case?

Another thing that I noticed:
https://github.com/jtpereyda/boofuzz/blob/583c8b291285cf0cdcf8b634113f738c518ad2e6/boofuzz/socket_connection.py#L161
should be
```python
raise exception.BoofuzzTargetConnectionFailedError(str(e))
```
but I doubt that this is related to your issue.

**Comment by starek4** [comment]
Now I tried it on the different environment and I got the same error after the first run. 

Target and fuzzer are on the same machine right now, but in the morning, I test it on two separate machines, so it does not matter.

Here is a video describing the error: https://youtu.be/KQkulZWv4ZA . Source code is the same as I post in the minimal example.

**Comment by SR4ven** [comment]
I still have no idea why a socket error comes up, but my guess is that a short sleep between the test cases could solve this.

As for the issue in the exception handling, that should be fixed with the PR I referenced.
@starek4 would be nice if you could confirm.

**Comment by starek4** [comment]
Your guess is right. My workaround now looks like this (works after #282 patch):
```
def post_test_callback(target, fuzz_data_logger, session, sock, *args, **kwargs):
    response_timeout = 2
    polling_interval = 0.005

    response = None
    for _ in range(0, int(response_timeout / polling_interval)):
        try:
            response = target.recv()
            break
        except exception.BoofuzzTargetConnectionReset:
            time.sleep(polling_interval)
            continue
```

It is not ideal, but it works.

**Comment by jtpereyda** [comment]
@starek4 I was just now able to read through this issue. It sounds like, after @SR4ven 's fixes, the error is now manifesting as `BoofuzzTargetConnectionReset` -- is that right? And the workaround is to ignore this error and keep on trying to receive?

**Comment by starek4** [comment]
@jtpereyda yes, exactly, now it raises BoofuzzTargetConnectionReset.

When the error occurs, usually the first sleep for 0.005 is enough (on both my environments) and then in the second recv you receive valid data.

**Comment by jtpereyda** [comment]
@starek4 I was able to reproduce the issue using your sample code and exactly duplicating the described environments. If I switch from WSL to an Ubuntu VM, the issue seems to go away. However, the issue is still visible if I switch the fuzzing Python instance to Python 2.7.16 instead of Python 3.

First, it seems that classifying ETIMEDOUT as a connection reset error was a mistake.

Second, I was perplexed as to why Windows was throwing the socket timeout error when the socket's recv timeout value should have been set. See this excerpt in `socket_connection.py`'s `open` method:
```
        self._sock.setsockopt(socket.SOL_SOCKET, socket.SO_SNDTIMEO, _seconds_to_second_microsecond_struct(self._send_timeout))
        self._sock.setsockopt(socket.SOL_SOCKET, socket.SO_RCVTIMEO, _seconds_to_second_microsecond_struct(self._recv_timeout))
```

I wrote a little test script to test socket timeouts on Windows:
```
from boofuzz import SocketConnection


connection=SocketConnection("127.0.0.1", 5050, proto='tcp')
connection.open()
connection.send("hello")
print(connection.recv(10000))
```
I ran this on Windows. For the server, I ran netcat on WSL: 
```
nc -nklvp 5050
```

The script exits immediately with `BoofuzzTargetConnectionReset`. This suggests that the timeout is not really being set at all. I haven't figured out how to resolve this yet.

**Comment by jtpereyda** [comment]
Looks like `SO_RCVTIMEO`'s data structure format varies with OS. I found this question: https://stackoverflow.com/questions/50723538/correct-value-for-python-socket-setsockopt-for-so-rcvtimeo-so-sndtimeo
which pointed to an MS reference: https://docs.microsoft.com/en-us/windows/desktop/WinSock/sol-socket-socket-options
which describes the format as a DWORD containing the number of milliseconds to wait before timing out. Another reference lists DWORD as an unsigned 32 bit value: https://docs.microsoft.com/en-us/windows/desktop/winprog/windows-data-types

I tried swapping format in without success so far. It might warrant further effort, but online everybody talks about using the `select()` method instead of setting the timeout, so that might be a better fix.

**Comment by jtpereyda** [comment]
To follow up on my last post, I found this guide online which helped enlighten me on sockets in general: http://beej.us/guide/bgnet/

Between this and some other references I can't remember, I think the solution is to use the select() method, but by now I've forgotten all the details.

Of course, a short term fix is not use the problematic environment, but that's kind of lame. :/

**Comment by starek4** [comment]
Yes, as a workaround I am using Linux docker containers or other forms of virtualization.
